version: '3'
services:
  nginx:
    hostname: am_web_server
    image: nginx:latest
    container_name: am_nginx
    ports:
      - "80:80"
      - "8080:8080"
    restart: always
    networks:
      - am_networks
    depends_on:
      - app
    volumes:
      - ./:/src
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
  mysql:
    hostname: am_db_server
    image: mysql:latest
    container_name: am_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: amdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/mysql-data:/var/lib/mysql"
      - ./storage/logs/mysql:/var/log/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - am_networks
  app:
    hostname: am_app_server
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    container_name: am_app
    environment:
      COMPOSER_MEMORY_LIMIT: '-1'
    ports:
      - "9912:9912"
    restart: always
    networks:
      - am_networks
    working_dir: /src
    volumes:
      - ./:/src:cached
  phpmyadmin:
    hostname: am_phpmyadmin_server
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    container_name: am_phpmyadmin
    depends_on:
      - mysql
    ports:
      - "3000:80"
    restart: always
    networks:
      - am_networks
    environment:
      PMA_HOST: am_db_server
      PMA_USER: root
      PMA_PASSWORD: password
      MEMORY_LIMIT: 256M
      UPLOAD_LIMIT: 128M

networks:
  default:
    external: true
    name: bridge
  am_networks:
    name: docker.internal